[bindings.kotlin]
package_name = "org.cooklang.sync"
generate_immutable_records = true
android = true

[bindings.swift]
ffi_module_name = "CooklangSyncFFI"
module_name = "CooklangSync"
generate_immutable_records = true
