[target.x86_64-linux-android]
linker = "x86_64-linux-android29-clang"
ar = "llvm-ar"
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.i686-linux-android]
linker = "i686-linux-android29-clang"
ar = "llvm-ar"
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi29-clang"
ar = "llvm-ar"
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.aarch64-linux-android]
linker = "aarch64-linux-android29-clang"
ar = "llvm-ar"
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.aarch64-apple-ios]
rustflags = ["-C", "link-args=-miphoneos-version-min=16.0"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-args=-mios-simulator-version-min=16.0"]

[target.x86_64-apple-ios]
rustflags = ["-C", "link-args=-mios-simulator-version-min=16.0"]
